### PR TITLE
Revert "Optimize images and add documentation with examples"

### PR DESCRIPTION
**Pull request by francisco-core**
Reverts PrivacyLx/website#25 @anadahz 

The compression was way too strong. We should revert this.

### CODE REVIEW

**Comment by anadahz** [comment]
@core I think you are zooming the image too much.
I don't see this image bad.

privacylx-org-1024x768desktop-20951b

I prefer that the website is loading faster than each user downloading an image of more than 8M !!

What could make sense perhaps is to use an SVG image or a different default image for posts.

Also why did you want to revert the changes to all images?

**Comment by francisco-core** [comment]
@anadahz because the compression is too high. If you compare it to the original it looks pretty bad. You can see compression artifacts all over the image.

**Comment by anadahz** [comment]
@francisco-core I suggest you to find another image.
Is is a huge bandwidth waste to have an image of > 8M in our homepage.

As I mentioned in https://github.com/PrivacyLx/website/pull/27#issuecomment-639171114 the other 20+ images are not negatively affected by the image optimization any reason why to also revert them to their original version?

**Comment by francisco-core** [comment]
> @francisco-core I suggest you to find another image.
> Is is a huge bandwidth waste to have an image of > 8M in our homepage.
> 
> As I mentioned in [#27 (comment)](https://github.com/PrivacyLx/website/pull/27#issuecomment-639171114) the other 20+ images are not negatively affected by the image optimization any reason why to also revert them to their original version?

I used the github interface because it was quicker. I've opened https://github.com/PrivacyLx/website/pull/33 to just replace this image.

**Comment by francisco-core** [comment]
deprecated by https://github.com/PrivacyLx/website/pull/33

**Pull request closed without merging**
