### PR TITLE
add opml

### PR DESCRIPTION
**Pull request by francisco-core**

### CODE REVIEW

**Comment by anadahz** [comment]
Thanks for this PR @francisco-core.
Please link the file to the website and it is good to go.

**Comment by francisco-core** [comment]
> Thanks for this PR @francisco-core. Please link the file to the website and it is good to go.

Where? I was thinking we could just link to this on your other PR. Not add it visually to the website.

**Comment by anadahz** [comment]
@francisco-core Let's link it somewhere. Let me know when you are ready with the PR so that we can add it in the README.

**Comment by francisco-core** [comment]
Spent a bunch of time trying to figure this out in a dynamic way. But didn't find a solution. So please do it the way you were doing before. Sorry for wasting your time.

**Comment by anadahz** [comment]
No worries @francisco-core, I reopened https://github.com/PrivacyLx/devops/pull/78 thx!

**Pull request closed without merging**
