### PR TITLE
Add discourse comments to every new post

### PR DESCRIPTION
**Pull request by francisco-core**
In #36 it was introduced the embedding of discourse comments from our forum on blog posts and events, but this required the manual addition of `{{< discourse-comments >}}` (a *shortcode* in hugo lingo) onto the posts's markdown.

This is now changed to show up automatically on every post/event (via *partials* in hugo lingo). It also has the addition that it will create automatically a post on the forum for the event/blog entry.

<strike>To avoid spamming the forum with new posts from all our past events at once, I have limited it so only posts after "2020-06-20" will have comments (thus create a blog post automagically).</strike> **edit:** Now one only has to add the metadata `comments: true`

It will look something like the following image

demo-comments

---

It's also safe to say that this will not work without javascript but does not affect the ability to view posts so I guess it is still fine

### CODE REVIEW

**Comment by francisco-core** [comment]
There is a slight problem with this PR: when we add posts in both languages it will create two different posts on the forum (one for each language)

**Comment by anadahz** [comment]
@francisco-core thank you for working on it.
I converted this PR to draft as it is WIP, feel free to change this when it's ready for review.

Is it possible to disable comments on a specific post/event?

**Comment by francisco-core** [comment]
> Is it possible to disable comments on a specific post/event?

Yes, that is possible. I will add a metadata tag to disable comments.

**Comment by francisco-core** [comment]
Ready for review @anadahz

**Comment by francisco-core** [comment]
@anadahz I have addressed it

**Comment by francisco-core** [comment]
this has been hanging here for a while. I'll merge it now. Hope that is fine @anadahz

**Pull request merged**
