### PR TITLE
Add RocketChat, list all #privacylx channel endpoints

### PR DESCRIPTION
**Pull request by anadahz**
Closes: https://github.com/PrivacyLx/privacylx-issue-tracker/issues/67

### CODE REVIEW

**Comment by francisco-core** [comment]
Thanks! I would prefer it it all went on the same line like so:

websss

If you like it, just merge the branch [add/rocketchat2](https://github.com/PrivacyLx/website/tree/add/rocketchat2) onto this one

**Comment by anadahz** [comment]
@francisco-core Great, yes it looks nicer this way.
You can just push your changes to this branch.

**Comment by francisco-core** [comment]
> @francisco-core Great, yes it looks nicer this way.
> You can just push your changes to this branch.

Done. Please merge it

**Comment by anadahz** [comment]
@francisco-core Done, thanks for the patch.

**Pull request merged**
