### PR TITLE
Add welcome pack page

### PR DESCRIPTION
**Pull request by anadahz**
Missing Portuguese version.

### CODE REVIEW

**Comment by francisco-core** [comment]
we should probably remove the `:heart:` from the text. And I also "obfuscated" the contact email. It may not be perfect since it has already been published here, but at least it is something. The less spam the better.

**Comment by francisco-core** [comment]
I also replace the link to our bylaws to the link to the about-us.

**Comment by anadahz** [comment]
@francisco-core Thanks for the Portuguese translation.
Is this good to merge?

**Review by francisco-core — COMMENTED** [review]
made some more changes. Now I think it's pretty much ready

**Comment by anadahz** [comment]
@francisco-core Great thanks.
I corrected some minor typos and merged.

**Comment by francisco-core** [comment]
thanks.

**Pull request merged**
